---
pool: default

schedules:
  - cron: '* * * * *'
    displayName: Daily midnight build 
    branches:
      include:
      - release
stages:
  - stage: 
    jobs:
      - job: 
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                git checkout adevops/develop
                git merge adevops/develop 
          - task: Bash@3
            inputs:
              targetType: inline 
              script: | 
                echo $(Agent.Name) 
                echo $(Build.BuildId)     
            